#!/bin/bash
javac Receiver.java

javac jniAES.java
javac jniRSA.java

gcc -c -fPIC AESLib.c
gcc -c -fPIC RSALib.c -lgmp

gcc -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux -fPIC -shared -z noexecstack jniAES.c AESLib.o -o libAESLib.so
gcc -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux -fPIC -shared -z noexecstack jniRSA.c RSALib.o -o libRSALib.so -lgmp
