/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniRSA */

#ifndef _Included_jniRSA
#define _Included_jniRSA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniRSA
 * Method:    genKeyRSA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jniRSA_genKeyRSA
  (JNIEnv *, jobject);

/*
 * Class:     jniRSA
 * Method:    encRSA
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jniRSA_encRSA
  (JNIEnv *, jobject, jbyteArray, jstring, jstring);

/*
 * Class:     jniRSA
 * Method:    decRSA
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jniRSA_decRSA
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
